# Use a lightweight Python 3.10 base image
FROM python:3.10-slim

# Set a working directory in the container
WORKDIR /app

# Copy the current directory's contents into the container
COPY . /app

# Install any required dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Command to run the script
CMD ["python", "streaming.py"]